version: '3'

services: 
  app:
    build: ./app
    ports:
      - "3000:3000"
    volumes: 
      - ./app:/usr/src/app
    restart: on-failure 
    links: 
      - mongo
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo
    command: mongod --port 9000
    ports: 
      - "9000:9000"


   